FROM debian:stable-slim

RUN apt-get update \
  && apt-get install -y ca-certificates \
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/

RUN mkdir -p /app/config
COPY target/release/notifications /app
COPY config /app/config
#COPY out /app/out

# Running as user "app"
RUN adduser --disabled-password --gecos "" --home /app --no-create-home -u 5000 app \
  && chown -R app: /app

USER app
WORKDIR /app
EXPOSE 8005

ENTRYPOINT ["/app/notifications"]
