version: '3'
services:
  notifications:
    image: notifications
    build:
      context: .
      dockerfile: Dockerfile.notif
    container_name: notifications
    working_dir: /app
    command: ["sh", "-c", "/utils/wait_for_it.sh notifications-pg:5432 ; diesel migration run ; cargo run"]
    volumes:
      - ..:/app
      - notifications_cargo_cache:/usr/local/cargo
    environment:
      - "DATABASE_URL=postgresql://notifications:notifications@notifications-pg/notifications"
      - "RUST_LOG=notifications=debug"
    expose:
      - 8005
    stdin_open: true
    depends_on:
      - notifications-pg
    links:
      - notifications-pg

  notifications-pg:
    image: postgres:10
    container_name: notifications-pg
    volumes:
      - stq-notifications-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=notifications
      - POSTGRES_DB=notifications
      - POSTGRES_PASSWORD=notifications
    expose:
      - 5432

volumes:
  notifications_cargo_cache:
  stq-notifications-postgres-data:

networks:
  default:
    external:
      name: storiqa
