FROM debian:stable-slim

RUN apt-get update
RUN apt-get install libssl1.1

# Cleaning up
RUN apt-get purge -y wget
RUN apt-get autoremove -y
RUN apt-get clean -y
RUN rm -rf /var/lib/apt/lists/

RUN mkdir -p /app/config
WORKDIR /app

COPY notifications /app
COPY config /app/config
EXPOSE 8005

ENTRYPOINT ["/app/notifications"]
